//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requisiciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int NoRequisicion { get; set; }
        public string Area { get; set; }
        public string Tipo { get; set; }
        public string EntregarEn { get; set; }
        public string Prioridad { get; set; }
        public System.DateTime FechaSurtido { get; set; }
        public string CompraServicio { get; set; }
    }
}
